apiVersion: apps/v1
kind: Deployment
metadata:
 name: petclinic-deployment
 labels:
    app: petclinic-app
spec:
 template:
    metadata:
     name: petclinic-pod
     labels:
        app: petclinic
    spec:
     containers:
        - name: petclinic
          image: mitesh51/petclinic:0.1 
 replicas: 1
 
 selector: 
    matchLabels:
        app: petclinic
---
apiVersion: v1
kind: Service
metadata:
 name: petclinic-service
 labels:
    app: petclinic
spec:
 selector: 
    app: petclinic
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 type: LoadBalancer
